define("MyPage_ListPage", /**SCHEMA_DEPS*/[]/**SCHEMA_DEPS*/, function/**SCHEMA_ARGS*/()/**SCHEMA_ARGS*/ {
	return {

		// --- How to configure a data grid and its summary row -----------------
		// crt.DataGrid renders a collection attribute. Its own config:
		//
		//   items              "$<CollectionAttribute>"
		//   primaryColumnName  the attribute holding the row id - REQUIRED, the
		//                      grid cannot select or delete rows without it
		//   columns            array of column definitions (below)
		//   features           what the grid allows:
		//       rows { selection, numeration }
		//       editable { enable, itemsCreation, floatingEditPanel }
		//   fitContent, visible, placeholder
		//
		// COLUMN DEFINITION:
		//   id            a guid, generated by the designer
		//   code          the ATTRIBUTE name for the column - it must exist in
		//                 the collection's viewModelConfig.attributes, otherwise
		//                 the cell is blank
		//   caption       "#ResourceString(<key>)#"
		//   dataValueType numeric type code (10 lookup, 29 text, 1 text, 4 int,
		//                 7 date-time, 12 boolean)
		//   sticky        true pins the column while scrolling horizontally
		//
		// SUMMARIES. crt.Summaries adds an aggregate row. Each summary column
		// carries an `expression` describing the aggregation:
		//
		//   "expression": {
		//       "expressionType": 1,          function expression
		//       "functionType": 2,            aggregation
		//       "aggregationType": 2,         SUM (1 COUNT, 2 SUM, 3 AVG,
		//                                     4 MIN, 5 MAX)
		//       "aggregationEvalType": 0,     over all rows
		//       "functionArgument": {
		//           "expressionType": 0,      column expression
		//           "columnPath": "QSAmountOfInvoice"
		//       }
		//   }
		//
		// The numeric codes are what the designer emits; treat the mapping above
		// as observed from generated schemas rather than as a published contract,
		// and prefer configuring summaries in the designer when you can.
		//
		// The collection itself is wired in viewModelConfigDiff - see
		// HowToWorkWithCollectionAttributes.js. Selection-driven actions use the
		// "<GridName>_SelectionState" attribute - see StockConvertersReference.js.

		viewConfigDiff: /**SCHEMA_VIEW_CONFIG_DIFF*/[

			{
				"operation": "insert",
				"name": "GridDetail_wttbyhd",
				"values": {
					"type": "crt.DataGrid",
					"items": "$GridDetail_wttbyhd",
					"primaryColumnName": "GridDetail_wttbyhdDS_Id",
					"visible": true,
					"fitContent": true,
					"placeholder": false,

					"features": {
						"rows": {
							"selection": true,
							"numeration": false
						},
						"editable": {
							"enable": false,
							"itemsCreation": false,
							"floatingEditPanel": false
						}
					},

					"columns": [
						{
							"id": "b647c669-015f-b640-835d-037419eeb525",
							"code": "GridDetail_wttbyhdDS_QSComplexAgreement",
							"caption": "#ResourceString(GridDetail_wttbyhdDS_QSComplexAgreement)#",
							"dataValueType": 10,
							"sticky": true
						},
						{
							"id": "1172b0f6-2f73-35d6-10b4-ba0a00b71c74",
							"code": "GridDetail_wttbyhdDS_QSClientName",
							"caption": "#ResourceString(GridDetail_wttbyhdDS_QSClientName)#",
							"dataValueType": 29
						}
					]
				},
				"parentName": "MainContainer",
				"propertyName": "items",
				"index": 0
			},

			// Aggregate row under the grid.
			{
				"operation": "insert",
				"name": "Summaries_invoices",
				"values": {
					"type": "crt.Summaries",
					"items": "$GridDetail_wttbyhd",
					"columns": [
						{
							"code": "GridDetail_wttbyhdDS_QSAmount",
							"caption": "#ResourceString(Summaries_invoices_total)#",
							"column": {
								"orderDirection": 0,
								"orderPosition": -1,
								"isVisible": true,
								"expression": {
									"expressionType": 1,
									"functionType": 2,
									"aggregationType": 2,
									"aggregationEvalType": 0,
									"functionArgument": {
										"expressionType": 0,
										"columnPath": "QSAmountOfInvoice"
									}
								}
							}
						}
					]
				},
				"parentName": "MainContainer",
				"propertyName": "items",
				"index": 1
			}

		]/**SCHEMA_VIEW_CONFIG_DIFF*/,

		viewModelConfigDiff: /**SCHEMA_VIEW_MODEL_CONFIG_DIFF*/[]/**SCHEMA_VIEW_MODEL_CONFIG_DIFF*/,
		modelConfigDiff: /**SCHEMA_MODEL_CONFIG_DIFF*/[]/**SCHEMA_MODEL_CONFIG_DIFF*/,
		handlers: /**SCHEMA_HANDLERS*/[]/**SCHEMA_HANDLERS*/,
		converters: /**SCHEMA_CONVERTERS*/{}/**SCHEMA_CONVERTERS*/,
		validators: /**SCHEMA_VALIDATORS*/{}/**SCHEMA_VALIDATORS*/

	};
});
